### ISSUE TITLE
Improve text search results by swapping " " with "+"

### ISSUE THREAD

**Issue by keikari** [Pigges/lbry-viewer#1]
For text param in claim search `spaces` seem to act like an OR, but `+` will act like an AND. 
Swapping spaces to + seems to improve results a lot.

**Comment by Pigges** [comment]
Hi. Thanks for letting me know.

I suppose you will need to replace `+` to something else if you want to search for something including a `+`?

**Comment by keikari** [comment]
On a quick try seems that just using `\+` works for that.

**Comment by Pigges** [comment]
Okay, will change this now.

**Comment by Pigges** [comment]
Fixed
